// Copyright 2026-2026 the openage authors. See copying.md for legal info.

#pragma once

#include <string>

#include "input/keys.h"


namespace openage::renderer {

/**
 * Input event of a window (key, mouse button, mouse move or wheel)
 * without a dependency on the window system (XR fork).
 *
 * Types, key codes, buttons and modifiers use the numeric values of Qt,
 * see input/keys.h. The Qt window converts its QEvents into this structure,
 * other window backends (e.g. an embedder without Qt) fill it directly.
 */
struct WindowEvent {
	/// Event type, see input::event_type.
	int type = input::event_type::NoEvent;

	/// Key code of key events, see input::key.
	int key = 0;

	/// Mouse button that caused a mouse button event, see input::mouse_button.
	int button = input::mouse_button::NoButton;

	/// All mouse buttons pressed during the event.
	int buttons = input::mouse_button::NoButton;

	/// Keyboard modifiers active during the event, see input::modifier.
	int modifiers = input::modifier::NoModifier;

	/// Mouse position in window coordinates (logical pixels).
	double x = 0.0;
	double y = 0.0;

	/// Mouse position in screen coordinates.
	double global_x = 0.0;
	double global_y = 0.0;

	/// Wheel rotation in eighths of a degree (120 = one wheel step).
	int angle_delta_x = 0;
	int angle_delta_y = 0;

	/// Text of key events (UTF-8), may be empty.
	std::string text{};

	/// True if a key event was generated by holding the key down.
	bool auto_repeat = false;
};

} // namespace openage::renderer
