# Copyright 2014-2026 the openage authors. See copying.md for legal info.

# set CODEGEN_SCU_FILE to the absolute path to SCU file
macro(get_codegen_scu_file)
	set(CODEGEN_SCU_FILE "${CMAKE_BINARY_DIR}/libopenage/codegen_scu.gen.cpp")
endmacro()

function(codegen_write_scu_file CODEGEN_TARGET_FILES)
	# write the single compilation unit that includes all generated .cpp files
	get_codegen_scu_file()
	get_filename_component(CODEGEN_SCU_DIR ${CODEGEN_SCU_FILE} DIRECTORY)

	set(CODEGEN_SCU_CONTENT "// Generated by codegen.\n\n")
	list(SORT CODEGEN_TARGET_FILES)
	foreach(target ${CODEGEN_TARGET_FILES})
		if("${target}" MATCHES "\.cpp$")
			file(RELATIVE_PATH target_rel ${CODEGEN_SCU_DIR} ${target})
			string(APPEND CODEGEN_SCU_CONTENT "#include \"${target_rel}\"\n")
		endif()
	endforeach()

	write_on_change(${CODEGEN_SCU_FILE} "${CODEGEN_SCU_CONTENT}")
endfunction()

function(codegen_copy_from_host)
	# XR fork: copy the codegen output of a host build (OPENAGE_CODEGEN_DIR)
	# instead of running the Python codegen, e.g. for cross builds without Python.
	# The host build must be built from the same commit (codegen_commit.txt).
	get_filename_component(HOST_DIR "${OPENAGE_CODEGEN_DIR}" REALPATH)
	set(HOST_LIST "${HOST_DIR}/codegen_generated_files")
	set(HOST_STAMP "${HOST_DIR}/codegen_commit.txt")

	foreach(required "${HOST_LIST}" "${HOST_STAMP}")
		if(NOT EXISTS "${required}")
			message(FATAL_ERROR "OPENAGE_CODEGEN_DIR=${OPENAGE_CODEGEN_DIR}: ${required} is missing. "
			                    "Build the host build (with Python) first.")
		endif()
	endforeach()

	file(STRINGS "${HOST_STAMP}" HOST_COMMIT LIMIT_COUNT 1)
	execute_process(
		COMMAND git rev-parse HEAD
		WORKING_DIRECTORY "${CMAKE_SOURCE_DIR}"
		OUTPUT_VARIABLE SOURCE_COMMIT
		RESULT_VARIABLE GIT_RESULT
		OUTPUT_STRIP_TRAILING_WHITESPACE
		ERROR_QUIET
	)
	if(NOT GIT_RESULT EQUAL 0)
		message(FATAL_ERROR "OPENAGE_CODEGEN_DIR: cannot determine the git commit of ${CMAKE_SOURCE_DIR}")
	endif()
	if(NOT "${HOST_COMMIT}" STREQUAL "${SOURCE_COMMIT}")
		message(FATAL_ERROR "OPENAGE_CODEGEN_DIR: codegen output of ${HOST_DIR} is from commit "
		                    "${HOST_COMMIT}, but the sources are at ${SOURCE_COMMIT}. "
		                    "Rebuild the host build at the same commit.")
	endif()

	file(STRINGS "${HOST_LIST}" HOST_FILES)
	set(CODEGEN_TARGET_FILES)
	foreach(host_file ${HOST_FILES})
		file(RELATIVE_PATH rel_file "${HOST_DIR}" "${host_file}")
		if(rel_file MATCHES "^\.\./" OR IS_ABSOLUTE "${rel_file}")
			message(FATAL_ERROR "OPENAGE_CODEGEN_DIR: ${host_file} is outside of ${HOST_DIR}")
		endif()
		set(target_file "${CMAKE_BINARY_DIR}/${rel_file}")
		# configure_file re-copies the file when it changes
		configure_file("${host_file}" "${target_file}" COPYONLY)
		list(APPEND CODEGEN_TARGET_FILES "${target_file}")
	endforeach()
	set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS "${HOST_LIST}" "${HOST_STAMP}")

	list(LENGTH CODEGEN_TARGET_FILES file_count)
	message(STATUS "codegen: copied ${file_count} files from ${HOST_DIR} (commit ${HOST_COMMIT})")

	# targets that other parts of the build depend on
	add_custom_target(cppgen)

	codegen_write_scu_file("${CODEGEN_TARGET_FILES}")
endfunction()

function(codegen_run)
	# this function must be called once all required assets have been created, but before the executable is finalized.

	# make sure this function gets called only once
	get_property(codegen_run GLOBAL PROPERTY SFT_CODEGEN_HAS_BEEN_RUN)
	if(codegen_run)
		message(FATAL_ERROR "codegen has already been run")
	endif()
	set_property(GLOBAL PROPERTY SFT_CODEGEN_HAS_BEEN_RUN 1)

	if(OPENAGE_CODEGEN_DIR)
		codegen_copy_from_host()
		return()
	endif()

	set(CODEGEN_INVOCATION
		"${PYTHON}" -m openage codegen
		"--input-dir=${CMAKE_SOURCE_DIR}"
		"--output-dir=${CMAKE_BINARY_DIR}"
		"--generated-list-file=${CMAKE_BINARY_DIR}/codegen_generated_files"
		"--depend-list-file=${CMAKE_BINARY_DIR}/codegen_depends")

	execute_process(COMMAND
		${CODEGEN_INVOCATION} --mode=dryrun
		WORKING_DIRECTORY "${CMAKE_BINARY_DIR}"
		RESULT_VARIABLE COMMAND_RESULT
	)

	if(NOT ${COMMAND_RESULT} EQUAL 0)
		message(FATAL_ERROR "failed to get target list from codegen invocation")
	endif()

	FILE(READ "${CMAKE_BINARY_DIR}/codegen_generated_files" CODEGEN_TARGET_FILES)
	FILE(READ "${CMAKE_BINARY_DIR}/codegen_depends" CODEGEN_DEPENDS)
	STRING(REGEX REPLACE "\n" ";" CODEGEN_TARGET_FILES ${CODEGEN_TARGET_FILES})
	STRING(REGEX REPLACE "\n" ";" CODEGEN_DEPENDS ${CODEGEN_DEPENDS})

	# as the codegen creates all files at once,
	# let the buildsystem only depend on this single dummy file.
	# otherwise the codegen invocation would be done for each generated source.
	set(CODEGEN_TIMEFILE "${CMAKE_BINARY_DIR}/codegen_timefile")

	add_custom_command(
		OUTPUT "${CODEGEN_TIMEFILE}"
		BYPRODUCTS ${CODEGEN_TARGET_FILES}
		COMMAND ${CODEGEN_INVOCATION} --mode=codegen "--touch-file-on-cache-change=${CMAKE_CURRENT_LIST_FILE}" --force-rerun-on-generated-list-change
		COMMAND "${CMAKE_COMMAND}" -E touch "${CODEGEN_TIMEFILE}"
		WORKING_DIRECTORY "${CMAKE_BINARY_DIR}"
		DEPENDS ${CODEGEN_DEPENDS}
		COMMENT "openage.codegen: generating c++ code"
	)

	add_custom_target(cppgen
		DEPENDS "${CODEGEN_TIMEFILE}"
	)

	add_custom_target(cleancodegen
		COMMAND ${CODEGEN_INVOCATION} --mode=clean
		COMMAND "${CMAKE_COMMAND}" -E remove "${CODEGEN_TIMEFILE}"
		WORKING_DIRECTORY "${CMAKE_BINARY_DIR}"
	)

	codegen_write_scu_file("${CODEGEN_TARGET_FILES}")

	# XR fork: commit stamp, lets builds without Python reuse this output
	# (OPENAGE_CODEGEN_DIR) only if they are at the same commit
	add_custom_target(codegen_commit ALL
		COMMAND "${CMAKE_COMMAND}"
			"-DSOURCE_DIR=${CMAKE_SOURCE_DIR}"
			"-DOUTPUT=${CMAKE_BINARY_DIR}/codegen_commit.txt"
			-P "${BUILDSYSTEM_DIR}/codegen_commit.cmake"
		COMMENT "codegen: storing commit stamp"
	)
	add_dependencies(codegen_commit cppgen)
endfunction()
